FROM node:alpine
ARG JENKINS_GID=1000
ARG JENKINS_UID=1000
RUN addgroup -S -g $JENKINS_GID jenkins
RUN adduser -D -S -u $JENKINS_UID -G jenkins jenkins
COPY confs/npmrc /home/jenkins/.npmrc
RUN chown -R jenkins:jenkins /home/jenkins
